- hosts: all
  sudo: yes
  gather_facts: no

  tasks:
  - name: ensure apt cache is up to date
    apt: update_cache=yes
  - name: ensure packages are installed
    apt: name={{item}}
    with_items:
        - postgresql
        - libpq-dev
        - python-psycopg2
- hosts: web1
  become: yes
  become_user: postgres
  gather_facts: no

  vars:
    dbname: db1
    dbuser: main-db
    dbpassword: leo

  tasks:
  - name: ensure database is created
    postgresql_db: name={{dbname}}

  - name: ensure user has access to database
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

///change the below
  - name: write our pg_hba.conf
    template: src=./pg_hba.conf.j2 dest=/etc/postgresql/9.3/main/pg_hba.conf
    notify: restart postgres

  handlers:

  - name: restart postgres
    service: name=postgresql state=restarted 